shinesolutions/puppet-aem-curator

- CHANGELOG.md
- manifests/config_author_primary.pp
- manifests/config_publish.pp
https://github.com/shinesolutions/aem-aws-stack-builder/issues/49
Modified CHANGELOG and edited config files to pass Travis CI test
> Regarding Issue#49 of aem-aws-stack-builder

- manifests/config_author_primary.pp
- manifests/config_publish.pp
Regarding Issue#49 of aem-aws-stack-builder
https://github.com/shinesolutions/aem-aws-stack-builder/issues/49
Modified config files to set variable jvm_mem_opts as undefined if not set.
> Feature aem jvm mem option

- CHANGELOG.md
- manifests/config_author_primary.pp
- manifests/config_author_standby.pp
Added condition to check if proxy env is set for collectd plugin
cloudwatch
Bug#28 https://github.com/shinesolutions/aem-aws-stack-provisioner/issues/28
> Added condition to check if proxy env is set for collectd plugin

- manifests/config_collectd.pp
Configure standby mbean only on standby component
> Modify collectd configuration

- CHANGELOG.md
- manifests/action_deploy_artifact.pp
- manifests/action_export_backup.pp
- manifests/action_export_backups.pp
- manifests/action_import_backup.pp
- manifests/action_promote_author_standby_to_primary.pp
- templates/aem-tools/export-backup.sh.epp
- templates/aem-tools/export-backups.sh.epp
- templates/aem-tools/import-backup.sh.epp
- templates/aem-tools/promote-author-standby-to-primary.sh.epp
Regarding issue https://github.com/shinesolutions/puppet-aem-curator/issues/15
> Integrated commands from aem-aws-stack-provisioner to aem-curator

- manifests/action_deploy_artifacts.pp
- manifests/config_author_dispatcher.pp
- manifests/config_publish_dispatcher.pp
Update variable name & added new variable name injected from provisioner.
> Updated variablename and added new ones to enable ssl

- manifests/action_promote_author_standby_to_primary.pp
Regarding issue https://github.com/shinesolutions/aem-aws-stack-provisioner/issues/64
> Add script execution to rename promoted Author Standby instances

- CHANGELOG.md
- manifests/install_author.pp
- manifests/install_publish.pp
* Add step to install collectd after installation of AEM for Author & Publish #71
> Add step to install collectd after for Author & Publish #71

- CHANGELOG.md
- manifests/config_collectd.pp
* Disable installation of collectd during stack provisioning #68
> Configure installation of collectd #68

- CHANGELOG.md
- manifests/action_deploy_artifact.pp
- manifests/action_deploy_artifacts.pp
- manifests/action_export_backup.pp
- manifests/action_export_backups.pp
- manifests/action_import_backup.pp
- manifests/action_list_packages.pp
- manifests/config_author_primary.pp
- manifests/config_publish.pp
- manifests/install_aem_package.pp
Add new check for AEM Package Manager readiness shinesolutions/aem-aws-stack-builder#214
> Add check AEM package manager shinesolutions/aem-aws-stack-builder#214

- CHANGELOG.md
- manifests/config_author_primary.pp
- manifests/config_publish.pp
Add credentials to last aem_health_check
> Add credentials to last aem_health_check

- CHANGELOG.md
- manifests/action_download_artifacts.pp
Add fix to only download artifacts if package state in the deployment descriptor files are set to present
> Add fix to in download artifacts manifest

- CHANGELOG.md
- manifests/action_promote_author_standby_to_primary.pp
- templates/aem-tools/promote-author-standby-to-primary.sh.epp
Add improvements to author-standby promotion script shinesolutions/aem-aws-stack-provisioner#155
> Add improvements to author-standby promotion script

- CHANGELOG.md
- files/crx-quickstart/install/org.apache.sling.jcr.base.internal.LoginAdminWhitelist.fragment-passwordreset.config
- manifests/config_author_primary.pp
- manifests/config_publish.pp
Add file copy to whitelist aem-password-bundle during AEM Startup shinesolutions/aem-aws-stack-builder#260
> Add file copy to whitelist aem-password-bundle

- manifests/action_promote_author_standby_to_primary.pp
- templates/aem-tools/promote-author-standby-to-primary.sh.epp
Fix parameter passing for aem_username & aem_password.
> Fix parameter passing for aem_username & aem_password.

- CHANGELOG.md
- manifests/reconfig_aem.pp
Fixed error in the reconfiguration logic #109
> Fixed error in the reconfiguration logic #109

- docs/aem-profiles-artifacts.md
- manifests/install_aem64_sp4.pp
Added aem64_sp4 installation Profile.
> Added new profile for installing AEM 6.4 with Service pack 4 - Fixes #117

- CHANGELOG.md
- templates/aem-tools/upgrade-aem-repo-migration.sh.epp
Fixed bug in repository migration script [#119]
> Fixed bug in repository migration script [#119]

- CHANGELOG.md
- manifests/action_disable_saml.pp
- manifests/action_enable_saml.pp
- manifests/config_aem_tools.pp
- manifests/config_saml.pp
- templates/aem-tools/disable-saml.sh.epp
- templates/aem-tools/enable-saml.sh.epp
Add new aem-tool enable-saml.sh
> Add new aem-tool enable-saml.sh

- CHANGELOG.md
- manifests/config_author_standby.pp
Update  permission on author-standby for mount point #141
> [author-standby] Update permissions of the mount point

- CHANGELOG.md
- manifests/upgrade_aem.pp
Removed AEM login page check after runing the AEM In-Place upgrade 
[#138]
> Removed AEM login page check after runing the AEM In-Place upgrade

- CHANGELOG.md
- manifests/action_config_aem.pp
- manifests/action_deploy_artifact.pp
- manifests/action_upgrade_aem_unpack_jar.pp
- manifests/config_aem.pp
- manifests/config_aem_crxde.pp
- manifests/config_aem_system_users.pp
- manifests/config_aem_tools.pp
**Added**
- Enforced translation of boolean parameters in various manifests 
shinesolutions/aem-aws-stack-builder#332
- Added boolean validation in various manifests 
shinesolutions/aem-aws-stack-builder#332
> Add verification of boolean parameters

- CHANGELOG.md
- templates/aem-tools/upgrade-aem-repo-migration.sh.epp
Add new InSpec test for repo migration [#147]
> Add new InSpec test for repo migration [#147]

- CHANGELOG.md
- manifests/config_author_primary.pp
- manifests/config_publish.pp
Fixed dependency issue during reconfiguration process [#156]
> Fixed dependency issue during reconfiguration process [#156]

- CHANGELOG.md
- manifests/install_dispatcher.pp
Add new data_volume for Author-Dispatcher , Publish-Dispatcher and Author-Publish-Dispatcher
> New Data Volume for Dispatcher 

- CHANGELOG.md
- manifests/install_dispatcher.pp
Added condition for create data_volume creation.
> Added condition to create data_volume

- CHANGELOG.md
- Gemfile
- manifests/config_aem_tools.pp
- templates/aem-tools/offline-compaction.sh.epp
checksum does not match for faraday 0.12.0 gem
https://github.com/lostisland/faraday/issues/679
> Fix offline compaction failure out of memory

- CHANGELOG.md
- Gemfile
- manifests/action_promote_author_standby_to_primary.pp
- manifests/config_author_primary.pp
- manifests/config_author_standby.pp
- manifests/config_publish.pp
- templates/config/jmx.properties.erb
- Added feature to enable SSL for JMX #RS-124
- Lockdown version of `concurrent-ruby` to `1.1.9` #RS-126
> Added feature to enable SSL for JMX

- CHANGELOG.md
- manifests/action_promote_author_standby_to_primary.pp
- manifests/config_aem_jmx.pp
- manifests/config_author_primary.pp
- manifests/config_author_standby.pp
- manifests/config_collectd.pp
- manifests/config_publish.pp
- templates/config/jmx.access
- templates/config/jmx.password
- templates/config/jmx.properties.erb
- Added feature to enable authentication for JMX #RS-125
- Added new Class to configure JMX for AEM #RS-125
- Changed component configuration manifest to use new Class `config_aem_jmx` to configure JMX for EM #RS-125
> Added feature to enable authentication for JMX #RS-125

- CHANGELOG.md
- manifests/install_aem.pp
- manifests/install_aem_package.pp
- Changed aem service management to systemd #RS-40
> Changed aem service management to systemd #RS-40

- CHANGELOG.md
- manifests/install_aem_java.pp
- manifests/install_java.pp
- JDK 371 Support Added #RS-146
> RS-146 Adds jdk8u371 support

- manifests/install_java.pp
- JDK 371 Support Added #RS-146
> RS-146 Adds jdk8u371 support for bare Java install

- CHANGELOG.md
- manifests/install_aem_java.pp
- manifests/install_java.pp
Fixing /usr/java directory permissions
> Fixing /usr/java/ directory permission

- CHANGELOG.md
- Fixing /usr/java directory permissions
> Fixing /usr/java directory permissions - CHANGELOG Updated

- manifests/action_content_sync_vlt.pp
- templates/aem-tools/content-sync-vlt.sh.epp
- Replaced port params with component conditions
> ContentSync: removed port params and added condition for component

- CHANGELOG.md
- manifests/action_content_sync_vlt.pp
- manifests/config_aem_tools.pp
- templates/aem-tools/content-sync-vlt.sh.epp
- Updated aem-config-tools to copy content-sync-vlt puppet template
> Updated aem-config-tools to copy content-sync-vlt puppet template

- CHANGELOG.md
- templates/aem-tools/content-sync-vlt.sh.epp
-  Content Sync: Usage details updated to match number of params
> Content Sync: Usage details updated to match number of params

- CHANGELOG.md
- manifests/action_attach_detach_content_sync_sg.pp
- templates/aem-tools/attach-detach-content-sync-sg.sh.epp
- templates/aem-tools/content-sync-vlt.sh.epp
- Content Sync: Fixed attach detach sg script with correct params
> Content Sync: Fixed attach detach sg script with correct params

- CHANGELOG.md
- manifests/action_content_sync_vlt.pp
- templates/aem-tools/content-sync-vlt.sh.epp
- Disabled debug mode in content-sync, write output in a log file
> RS-179 Disabled debug mode in content-sync

- CHANGELOG.md
- templates/aem-tools/attach-detach-content-sync-sg.sh.epp
- templates/aem-tools/content-sync-vlt.sh.epp
- Made exclude_parameter optional for content-sync script #RS-179
- Fixes retrieval of content sync sg in attach sg script #RS-179
> Fixes for content sync 

- manifests/config_author_primary.pp
- manifests/config_publish.pp
To fix issue https://github.com/shinesolutions/puppet-aem-curator/issues/283
> Make sure LoginAdminWhitelist.fragment-passwordreset.config is installed before aem-password-rest package

- .rtk.json
- CHANGELOG.md
- Fixed incorrect syntax in RTK config file
> Corrects RTK config

- .github/actions/ci-action/Dockerfile
- .github/actions/publish-action/Dockerfile
- .github/actions/publish-action/entrypoint.sh
- .github/actions/release-major-action/Dockerfile
- .github/actions/release-major-action/entrypoint.sh
- .github/actions/release-minor-action/Dockerfile
- .github/actions/release-minor-action/entrypoint.sh
- .github/actions/release-patch-action/Dockerfile
- .github/actions/release-patch-action/entrypoint.sh
- CHANGELOG.md
- Lock aem-platform-buildenv to 4.0.1
- Explicitly set ownership of github workspace directory
> Resolve release issues

- CHANGELOG.md
- manifests/install_aem_java.pp
- manifests/install_java.pp
- Add support for JDK 8u421
- Add support for JDK 11.0.24
> Add JDK Support
